excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://KramKroc.github.io
title: Mark Corkery
tagline: A log of everyday life
description: Sometimes technical, always random!
paginate: 5
theme: jekyll-theme-prologue
twitter_username: KramKroc

gems:
  - jekyll-mentions
  - jekyll-sitemap
