excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://KramKroc.github.io
title: Mark Corkery
tagline: A log of everyday life
description: Sometimes technical, always random!
paginate: 5
baseurl: "https://github.com/kramkroc/kramkroc.github.io/blob/master"
